### ISSUE TITLE
undefined method `default_client' for Mongoid:Module

### ISSUE THREAD

**Issue by JIucToyxuu** [DatabaseCleaner/database_cleaner#440] opened 2016-04-22 11:23 UTC
Hello!

I got "undefined method `default_client' for Mongoid:Module" error after update DatabaseCleaner to latest version. This happened when I launch rspec tests, after DatabaseCleaner[:mongoid].clean
I see what code was updated [https://github.com/DatabaseCleaner/database_cleaner/commit/0a2bef7c878c14afe01791353df717e3ef969814], but not sure what this can be reason for this.

Ruby- 2.1.2 or 2.2.1 (try both)
Rails - 4.1.15
Mongoid version - 4.0.2
DatabaseCleaner - 1.5.2

Are there any thoughts?
P.S. Excuse me for bad English.

**Comment by etagwerker** [comment] 2016-04-22 11:37
This is a duplicate of https://github.com/DatabaseCleaner/database_cleaner/issues/436

Please use `master` at bc16ceee741a8b8912f1006b6cb2d0682946910c and try again. There is a new release coming soon.

**Closed by etagwerker** 2016-04-22 11:37 UTC
