### ISSUE TITLE
Got weird error with multiple ORM's in master branch

### ISSUE THREAD

**Issue by takashi** [DatabaseCleaner/database_cleaner#295] opened 2014-11-10 14:11 UTC
I got `The 'truncation' strategy does not exist for the mongoid ORM!  Available strategies: truncation (DatabaseCleaner::UnknownStrategySpecified)`

in my spec_helper

```ruby
config.before(:suite) do
    DatabaseCleaner.clean_with :truncation
    DatabaseCleaner.strategy = :truncation
    DatabaseCleaner[:mongoid].strategy = :truncation
end
```

Then I changed my gem file

`gem 'database_cleaner', github: 'DatabaseCleaner/database_cleaner'` to `gem 'database_cleaner', '~> 1.3.0'`,  the error never occurred. 

Is there any bug in master branch?

**Comment by gurix** [comment] 2015-01-05 14:47
duplicate of #299

**Comment by etagwerker** [comment] 2015-07-01 02:14
@takashi version 1.4.1 should fix this.

**Closed by etagwerker** 2015-07-01 02:14 UTC

**Comment by takashi** [comment] 2015-07-01 03:29
@etagwerker thank you for fixing!
