### ISSUE TITLE
Safeguards with SQLite

### ISSUE THREAD

**Issue by sandelius** [DatabaseCleaner/database_cleaner#548] opened 2018-05-02 09:33 UTC
When using SQLite, e.g `DATABASE_URL=sqlite:///path/to/database.db` the safeguards raises the error since `localhost` is not part of the URL. This should not happen.

**Comment by etagwerker** [comment] 2018-05-02 13:07
This is a duplicate of https://github.com/DatabaseCleaner/database_cleaner/issues/528

Please use `master` until a new release is published.

**Closed by etagwerker** 2018-05-02 13:07 UTC
