### ISSUE TITLE
1.4.0 except is broken

### ISSUE THREAD

**Issue by PeterMozesMerl** [DatabaseCleaner/database_cleaner#326] opened 2015-01-10 21:52 UTC
I have the following lines in my rails_helper.rb

```ruby
DatabaseCleaner.strategy = :truncation, {except: %w[zodiac_signs]}
DatabaseCleaner.strategy = :truncation, {except: %w[zodiac_signs] + tables_not_to_clean}
```

When I upgraded to 1.4.0 my Capybara features failed. The rails console test shows:

```ruby
DatabaseCleaner.clean_with(:truncation, {except: %w[zodiac_signs]})

(76.3ms)  TRUNCATE TABLE "public"."cities", [...], "public"."zodiac_signs", [...] RESTART IDENTITY CASCADE;
```

Downgrading to 1.3.0 solves the issue.

Rails 4.2, Ruby 2.1.5, Postgresql 9.4

**Comment by dkastner** [comment] 2015-01-12 19:52
I can confirm:

``` ruby
DatabaseCleaner.strategy = :deletion, {                  
  except: %w{ spatial_ref_sys }
}                                                        
```


Test error:

```
     ActiveRecord::StatementInvalid:
       PG::InternalError: ERROR:  GetProj4StringSPI: Cannot find SRID (4326) in spatial_ref_sys
```

**Comment by mmclead** [comment] 2015-01-13 18:36
Having same issue.

**Comment by philostler** [comment] 2015-01-19 18:36
+1 Same issue here as well

**Comment by jwallerf** [comment] 2015-01-20 16:52
Having the same issue also.

**Comment by Supro** [comment] 2015-01-27 15:01
Got this problem after migrating to database_cleaner version 1.4.0

``` ruby
  config.before(:suite) do
    DatabaseCleaner.strategy = :deletion, { except: %w[spatial_ref_sys] }
    DatabaseCleaner.clean_with :truncation, { except: %w[spatial_ref_sys] }
  end
```

``` bash
  ActiveRecord::StatementInvalid:
     PG::InternalError: ERROR:  GetProj4StringSPI: Cannot find SRID (4326) in spatial_ref_sys
```

**Comment by skyeagle** [comment] 2015-02-09 14:07
It looks like for Rails 4.2 these options should include schema. For example:

```ruby
DatabaseCleaner.clean_with :truncation, { except: %w[public.table_name] }
```

**Comment by thomasfedb** [comment] 2015-03-04 17:18
Same issue here. The suggestion above from @skyeagle resolved the problem in my case.

**Comment by etagwerker** [comment] 2015-03-09 14:53
Has anyone tested this issue with `master`? I believe that it's been fixed with PR #328. Please confirm.

**Comment by philss** [comment] 2015-03-10 21:06
@etagwerker I tested against version 1.4.1 and it works! Thanks!

**Comment by larryh** [comment] 2015-04-02 21:06
Hi,

It's not working for me in v1.4.1. (Rails 4.0.5 and MySQL and Cucumber)

This is what I have in my features/support/database_cleaner.rb file:
DatabaseCleaner.strategy = :truncation, { except: %w(activities notifications), pre_count: true }

And here are some lines from the test.log file:

  [1m[35m (9.4ms)[0m  TRUNCATE TABLE `activities`;
  [1m[36m (3.5ms)[0m  [1mTRUNCATE TABLE `activity_points`;[0m
- - - - -
  [1m[36m (3.6ms)[0m  [1mTRUNCATE TABLE `newsletter_themes`;[0m
  [1m[35m (1.8ms)[0m  TRUNCATE TABLE `notifications`;
  [1m[36m (3.9ms)[0m  [1mTRUNCATE TABLE `oauth_access_tokens`;[0m

As you can see, both the 'activities' and 'notifications' tables are getting truncated. 

I tried using :delete instead of :truncation and that did not work.

Am I doing something wrong?

**Comment by etagwerker** [comment] 2015-10-16 19:03
@larryh Could you paste all of your code here?

**Comment by larryh** [comment] 2015-10-19 16:03
Hi,

I no longer have the code that I mentioned above, and my DatabaseCleaner gem is now at 1.5.0, so there's really nothing that I can paste.

**Closed** 2015-10-19 16:17 UTC
